drop table if exists EVENT;


CREATE TABLE IF NOT EXISTS EVENT
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
    app     varchar(1024),
    uri     varchar(1024),
    ip      varchar(1024),
    created TIMESTAMP WITHOUT TIME ZONE
)

